# Generated by Django 5.1 on 2026-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('kategori', models.CharField(choices=[('balita', 'Balita & Anak'), ('psikologi', 'Psikologi Anak'), ('remaja', 'Remaja & Digital'), ('keluarga', 'Keluarga Sakinah')], max_length=20)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='artikel/')),
                ('penulis', models.CharField(default='Tim AsuhBijak', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibaca', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('psikolog', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(max_length=10)),
                ('topik', models.TextField()),
                ('metode', models.CharField(choices=[('video', 'Video Call - Rp175.000'), ('chat', 'Chat Konsultasi - Rp125.000'), ('telepon', 'Telepon - Rp150.000')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Terkonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('wa_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranTaaruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('domisili', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('pendidikan', models.CharField(blank=True, max_length=50)),
                ('kriteria_pasangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('contacted', 'Sudah Dihubungi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('wa_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
