# Generated by Django 5.1 on 2026-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelasOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('kelas_id', models.IntegerField()),
                ('kelas_nama', models.CharField(max_length=200)),
                ('kelas_harga', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kartu Kredit'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('midtrans', 'Midtrans')], default='midtrans', max_length=20)),
                ('payment_gateway', models.CharField(choices=[('midtrans', 'Midtrans'), ('xendit', 'Xendit'), ('tripay', 'Tripay')], default='midtrans', max_length=20)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('processing', 'Diproses'), ('paid', 'Lunas'), ('expired', 'Kadaluarsa'), ('cancelled', 'Dibatalkan'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
